"""add_role_to_users

Revision ID: b2a7faf0ef8c
Revises: 936336932a85
Create Date: 2026-03-06 11:51:49.320266
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2a7faf0ef8c'
down_revision: Union[str, None] = '936336932a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
