"""init

Revision ID: ed3c0eec8c2d
Revises: 
Create Date: 2026-03-05 16:11:00.212354
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ed3c0eec8c2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.Enum('KEYWORDS', 'COMPETITOR', 'CONTENT', 'AUDIT', 'FULL', 'STRATEGY', 'FIX', name='reportmodule'), nullable=False),
    sa.Column('input_query', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STREAMING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('letter_grade', sa.String(length=5), nullable=True),
    sa.Column('quick_wins', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tech_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('estimated_traffic', sa.Integer(), nullable=True),
    sa.Column('domain_authority', sa.Integer(), nullable=True),
    sa.Column('top_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('title_tag', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('target_word_count', sa.Integer(), nullable=True),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lsi_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snippet_strategy', sa.Text(), nullable=True),
    sa.Column('eeat_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('target_rank', sa.Integer(), nullable=True),
    sa.Column('competitor_ranks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('keyword_difficulty', sa.Integer(), nullable=True),
    sa.Column('search_intent', sa.String(length=50), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('is_golden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_result_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fix_suggestion', sa.Text(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('effort_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['audit_result_id'], ['audit_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_issues')
    op.drop_table('keywords')
    op.drop_table('keyword_gaps')
    op.drop_table('content_briefs')
    op.drop_table('competitors')
    op.drop_table('audit_results')
    op.drop_table('reports')
    op.drop_table('projects')
    # ### end Alembic commands ###
